version: '3.8'
services:
#PHP Services
  laravel:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: default/laravel
    container_name: test-laravel
    restart: unless-stopped
    tty: true
    env_file:
        - .env
    environment:
      SERVICE_NAME: test-laravel
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - default_network

#Nginx Service
  webserver:
    image: nginx:alpine
    container_name: test-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
      - "445:443"
    volumes:
      - ./:/var/www
      - ./docker-configs/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default_network

networks:
  default_network:
    driver: bridge